export const FETCH_STOCKS_SUCCEEDED = 'FETCH_STOCKS_SUCCEEDED';
export const FETCH_STOCKS_FAILED = 'FETCH_STOCKS_FAILED';
export const FETCH_STOCKS_REQUESTED = 'FETCH_STOCKS_REQUESTED';
export const SET_STOCKS = 'SET_STOCKS';
